### PR TITLE
Implemented SystemLoader Module

### PR DESCRIPTION
**Pull request by GhadirCliqz**
- Implemented the SystemLoader module.
- It has been tested on iOS 8, 9 and 10.
- Added the v8 assets to iOS.
@sam-cliqz @mahmoud-cliqz please review it and let me know if something should be changed.

### CODE REVIEW

**Comment by ghost** [comment]
We already have the built js files inside the android project. Would be it possible to only have this code once in the repo and copy/link it into place during the build?

**Comment by GhadirCliqz** [comment]
@sam-cliqz Done, I merged the `master` with `ios`. However, locally I don't have any conflicts but here it shows that there are some conflicts.

**Comment by ghost** [comment]
@GhadirCliqz are you up to date with ios branch too? That's probably what's causing conflicts?

**Comment by GhadirCliqz** [comment]
@sam-cliqz yes, I am.

**Pull request merged**
