### PR TITLE
JS performance improvements for Adblocker

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@remi-cliqz the adblocker doesn't seem to load properly after this change. Does it look correctly merged to you?

**Comment by ghost** [comment]
@zhonghao-cliqz could you have a look?

**Comment by ghost** [comment]
@sam-cliqz Hey, sorry for the delay, I did not check my mails last week... I just had a quick look, and the merge looks suspicious. It seems that some parts of the code come from an older version, and some from the very new master? For example the old name of the class for cosmetic filters was `AdCosmetics` and the new change is using `CosmeticFilter` instead (which is the name on current master), but the name of the class defined in the code is still `AdCosmetics`. I think we mixed the very new master with an older version. Not sure how it happened.

**Comment by zhonghao-cliqz** [comment]
I made a pr to navigation-extension to fix this loading of adblocker https://github.com/sam-cliqz/navigation-extension/pull/11

**Comment by ghost** [comment]
Updated this branch with build from @zhonghao-cliqz changes.

**Pull request merged**
